id: default
config:
  parse:
    do_ocr: False
    force_ocr: False
    ocr_engine: easyocr
    ocr_lang: en
    pdf_backend: pypdfium2
    table_mode: accurate
    do_picture_description: True
  chunk:
    chunker: docling-serve
    chunk_size: 256
    text_context_radius: 0
    chunker_type: hybrid
  embed:
    provider: ollama
    model: qwen3-embedding:4b
    vector_dim: 2560
  store:
    data_dir: s3://soliplex-lancedb/s3_default2
