id: test_diff_chunk
name: test with parse chunk and embed different chunk param
config:
  parse:
    parse_param: parse_param_base
  chunk:
    chunk_param: chunk_param2
  embed:
    embed_param: embed_param_base
